### ISSUE TITLE
memory issues on iphone 6 

### ISSUE THREAD

**Issue by doston0000** [regulaforensics/DocumentReader-iOS#36]
first photo after db init 
<img width="1191" alt="Screen Shot 2021-04-01 at 12 34 32 PM" src="https://user-images.githubusercontent.com/16070841/113259487-9e3f1600-92e6-11eb-969f-4732f84d203c.png">

then after pressing show scanner 
<img width="1359" alt="Screen Shot 2021-04-01 at 12 35 15 PM" src="https://user-images.githubusercontent.com/16070841/113259571-b747c700-92e6-11eb-9530-6566e37f764a.png">

**Comment by vyakimchik** [comment]
Hello,

Yes, it seems that it's due to insufficient memory. As this device has only 1GB of RAM and the app with full SDK and full database consumes approximately 400-500 MB, it may crash as other apps also consume some part of memory. What we can suggest is to use the custom database that will include only those documents of those countries you need. Also, you can use the Core type with the functionality you need. E.g. if you want to get data only from MRZs, it's enough for you to use the MRZ [Core](https://docs.regulaforensics.com/ios/core) type, and the database isn't needed at all.

Could you please describe your use case so that we can suggest the Core type and the database that meet your needs?
