### ISSUE TITLE
[BR] TMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted.

### ISSUE THREAD

**Issue by MoElnaggar14** [regulaforensics/DocumentReader-iOS#66]
**Before Submitting, be sure to**
- [x] Update to the latest stable version.
- [x] Read and follow the guides described in the [documentation](https://docs.regulaforensics.com?utm_source=github).
- [ ] Try to reproduce in our demo project.
- [x] Search for your issue in the existing GitHub issues.

**Bug Description**
TMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

when we execute `grep -r "UIWebView" .` we get the match from the pod
<img width="1406" alt="image" src="https://github.com/regulaforensics/DocumentReader-iOS/assets/21294763/dd328930-73aa-4265-bdbd-bce2550b57c2">

**Steps To Reproduce**

**Expected behavior**

**Screenshots**

**Environment:**
 - Device: 
 - OS version: 

**Additional context**

**Comment by vyakimchik** [comment]
Hi @MoElnaggar14,

.dSYM files don't contain any functional code. This is debugging metadata. The reason why you've found this mention of `UIWebView` in our dSYM files is because we link to UIKit and the version of iOS that may include `UIWebView`.

`UIWebView` don't exist in our frameworks that can be confirmed by running the following command:
```
nm /DocumentReader.framework/DocumentReader | grep -i UIWebView
```
This returns no results. We deliver apps to TestFlight and App Store and haven't come across this warning ourselves.
